In [3]:
l = [132352, 46524, 54325, 14243, -9325]

In [4]:
l

[132352, 46524, 54325, 14243, -9325]

In [5]:
import numpy as np

In [6]:
a = np.array(l)

In [7]:
a

array([132352,  46524,  54325,  14243,  -9325])

In [8]:
b = np.array([12, 455, 65.3, True, 'abc',])

In [9]:
print(b)

['12' '455' '65.3' 'True' 'abc']


In [10]:
a.mean()

47623.800000000003

---

In [11]:
# 3-20: slicing arrays

In [12]:
a[:2]

array([132352,  46524])

In [13]:
a[2:4]

array([54325, 14243])

In [14]:
b = a[2:4]

In [15]:
b

array([54325, 14243])

In [16]:
b[0]

54325

In [17]:
b[:]

array([54325, 14243])

In [18]:
b[:] = 111

In [19]:
b

array([111, 111])

In [20]:
a

array([132352,  46524,    111,    111,  -9325])

In [21]:
c = a.copy()

In [22]:
c[0] = 0

In [23]:
c

array([    0, 46524,   111,   111, -9325])

In [24]:
a

array([132352,  46524,    111,    111,  -9325])